name = "cms-cache"
main = "index.js"
compatibility_date = "2023-12-14"

# Supply Account ID in the CF_ACCOUNT_ID environment variable
# Supply Zone    ID in the CF_ZONE_ID    environment variable
routes     = [
    "cms.regalradio.net/api/shows*",
    "cms.regalradio.net/api/date*",
    "cms.regalradio.net/api/sponsors*",
    "cms.regalradio.net/api/schedule*",
    "cms.regalradio.net/api/persons*"
]