name = "cms-cache"
type = "javascript"

# Supply Account ID in the CF_ACCOUNT_ID environment variable
# Supply Zone    ID in the CF_ZONE_ID    environment variable
routes     = [
    "cms.regalradio.net/shows*",
    "cms.regalradio.net/date*",
    "cms.regalradio.net/sponsors*",
    "cms.regalradio.net/schedule*",
    "cms.regalradio.net/persons*"
]