name: Deploy Worker

on:
  push:
    branches: [ main ]
    paths-ignore:
        - '.github/**'
        - 'README.md'
  workflow_dispatch: 

jobs:
   deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_ZONE_ID:    ${{ secrets.CLOUDFLARE_ZONE_ID }}
